/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certification {
  'id' : bigint,
  'url' : [] | [string],
  'dateEarned' : string,
  'name' : string,
  'issuer' : string,
}
export interface EducationEntry {
  'id' : bigint,
  'field' : string,
  'endDate' : [] | [string],
  'institution' : string,
  'degree' : string,
  'startDate' : string,
}
export interface ExperienceEntry {
  'id' : bigint,
  'title' : string,
  'endDate' : [] | [string],
  'description' : string,
  'company' : string,
  'achievements' : Array<string>,
  'location' : string,
  'startDate' : string,
}
export type Modality = { 'ilt' : null } |
  { 'eLearning' : null } |
  { 'hybrid' : null } |
  { 'jobAid' : null };
export interface Project {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : [] | [string],
  'challenge' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'results' : string,
  'modality' : Modality,
  'approach' : string,
  'deliverables' : Array<string>,
}
export interface Resume {
  'linkedIn' : [] | [string],
  'title' : string,
  'name' : string,
  'education' : Array<EducationEntry>,
  'email' : string,
  'website' : [] | [string],
  'experience' : Array<ExperienceEntry>,
  'summary' : string,
  'phone' : [] | [string],
  'certifications' : Array<Certification>,
  'skills' : Array<Skill>,
  'location' : string,
}
export interface Skill { 'id' : bigint, 'name' : string, 'category' : string }
export interface TailoredView {
  'slug' : string,
  'label' : string,
  'privateCompany' : string,
  'privateJobDescription' : string,
  'primaryLane' : string,
  'lanes' : Array<string>,
  'projectIds' : Array<string>,
  'proofIds' : Array<string>,
  'skillIds' : Array<string>,
  'angle' : string,
  'expiresAt' : [] | [string],
  'createdAt' : bigint,
  'archived' : boolean,
}
export interface TailoredViewInput {
  'slug' : string,
  'label' : string,
  'privateCompany' : string,
  'privateJobDescription' : string,
  'primaryLane' : string,
  'lanes' : Array<string>,
  'projectIds' : Array<string>,
  'proofIds' : Array<string>,
  'skillIds' : Array<string>,
  'angle' : string,
  'expiresAt' : [] | [string],
}
export interface _SERVICE {
  '__projects' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Project>>,
  '__resume' : ActorMethod<[], any>,
  'addProject' : ActorMethod<[Project], undefined>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getResume' : ActorMethod<[], [] | [Resume]>,
  'getTailoredView' : ActorMethod<[string], [] | [TailoredView]>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'listTailoredViews' : ActorMethod<[], Array<TailoredView>>,
  'seedPortfolio' : ActorMethod<[], undefined>,
  'seedResume' : ActorMethod<[], undefined>,
  'saveTailoredView' : ActorMethod<[TailoredViewInput], TailoredView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
