/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Modality = IDL.Variant({
  'ilt' : IDL.Null,
  'eLearning' : IDL.Null,
  'hybrid' : IDL.Null,
  'jobAid' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'challenge' : IDL.Text,
  'createdAt' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'results' : IDL.Text,
  'modality' : Modality,
  'approach' : IDL.Text,
  'deliverables' : IDL.Vec(IDL.Text),
});
export const EducationEntry = IDL.Record({
  'id' : IDL.Nat,
  'field' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Text),
  'institution' : IDL.Text,
  'degree' : IDL.Text,
  'startDate' : IDL.Text,
});
export const ExperienceEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'company' : IDL.Text,
  'achievements' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Certification = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Opt(IDL.Text),
  'dateEarned' : IDL.Text,
  'name' : IDL.Text,
  'issuer' : IDL.Text,
});
export const Skill = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'category' : IDL.Text,
});
export const Resume = IDL.Record({
  'linkedIn' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'name' : IDL.Text,
  'education' : IDL.Vec(EducationEntry),
  'email' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'experience' : IDL.Vec(ExperienceEntry),
  'summary' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'certifications' : IDL.Vec(Certification),
  'skills' : IDL.Vec(Skill),
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '__projects' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Project)],
      ['query'],
    ),
  '__resume' : IDL.Func([], [IDL.Reserved], ['query']),
  'addProject' : IDL.Func([Project], [], []),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getResume' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'seedPortfolio' : IDL.Func([], [], []),
  'seedResume' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Modality = IDL.Variant({
    'ilt' : IDL.Null,
    'eLearning' : IDL.Null,
    'hybrid' : IDL.Null,
    'jobAid' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'challenge' : IDL.Text,
    'createdAt' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'results' : IDL.Text,
    'modality' : Modality,
    'approach' : IDL.Text,
    'deliverables' : IDL.Vec(IDL.Text),
  });
  const EducationEntry = IDL.Record({
    'id' : IDL.Nat,
    'field' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Text),
    'institution' : IDL.Text,
    'degree' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const ExperienceEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'company' : IDL.Text,
    'achievements' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Certification = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Opt(IDL.Text),
    'dateEarned' : IDL.Text,
    'name' : IDL.Text,
    'issuer' : IDL.Text,
  });
  const Skill = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'category' : IDL.Text,
  });
  const Resume = IDL.Record({
    'linkedIn' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'name' : IDL.Text,
    'education' : IDL.Vec(EducationEntry),
    'email' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'experience' : IDL.Vec(ExperienceEntry),
    'summary' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
    'certifications' : IDL.Vec(Certification),
    'skills' : IDL.Vec(Skill),
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '__projects' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Project)],
        ['query'],
      ),
    '__resume' : IDL.Func([], [IDL.Reserved], ['query']),
    'addProject' : IDL.Func([Project], [], []),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getResume' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'seedPortfolio' : IDL.Func([], [], []),
    'seedResume' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };