/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Certification {
    id: bigint;
    url?: string;
    dateEarned: string;
    name: string;
    issuer: string;
}
export interface Skill {
    id: bigint;
    name: string;
    category: string;
}
export interface Resume {
    linkedIn?: string;
    title: string;
    name: string;
    education: Array<EducationEntry>;
    email: string;
    website?: string;
    experience: Array<ExperienceEntry>;
    summary: string;
    phone?: string;
    certifications: Array<Certification>;
    skills: Array<Skill>;
    location: string;
}
export interface Project {
    id: bigint;
    title: string;
    thumbnailUrl?: string;
    challenge: string;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    results: string;
    modality: Modality;
    approach: string;
    deliverables: Array<string>;
}
export interface ExperienceEntry {
    id: bigint;
    title: string;
    endDate?: string;
    description: string;
    company: string;
    achievements: Array<string>;
    location: string;
    startDate: string;
}
export interface EducationEntry {
    id: bigint;
    field: string;
    endDate?: string;
    institution: string;
    degree: string;
    startDate: string;
}
export enum Modality {
    ilt = "ilt",
    eLearning = "eLearning",
    hybrid = "hybrid",
    jobAid = "jobAid"
}
export interface backendInterface {
    __projects(io: bigint | null, count: bigint | null): Promise<Array<Project>>;
    __resume(): Promise<any>;
    addProject(project: Project): Promise<void>;
    getProject(id: bigint): Promise<Project | null>;
    getResume(): Promise<Resume | null>;
    listProjects(): Promise<Array<Project>>;
    seedPortfolio(): Promise<void>;
    seedResume(): Promise<void>;
}
import type { Certification as _Certification, EducationEntry as _EducationEntry, ExperienceEntry as _ExperienceEntry, Modality as _Modality, Project as _Project, Resume as _Resume, Skill as _Skill } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __projects(arg0: bigint | null, arg1: bigint | null): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.__projects(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__projects(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __resume(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__resume();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__resume();
            return result;
        }
    }
    async addProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(to_candid_Project_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(to_candid_Project_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResume(): Promise<Resume | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResume();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResume();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedPortfolio(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedPortfolio();
            return result;
        }
    }
    async seedResume(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedResume();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedResume();
            return result;
        }
    }
}
function from_candid_Certification_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Certification): Certification {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_EducationEntry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EducationEntry): EducationEntry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ExperienceEntry_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceEntry): ExperienceEntry {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Modality_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Modality): Modality {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Resume_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resume): Resume {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resume]): Resume | null {
    return value.length === 0 ? null : from_candid_Resume_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedIn: [] | [string];
    title: string;
    name: string;
    education: Array<_EducationEntry>;
    email: string;
    website: [] | [string];
    experience: Array<_ExperienceEntry>;
    summary: string;
    phone: [] | [string];
    certifications: Array<_Certification>;
    skills: Array<_Skill>;
    location: string;
}): {
    linkedIn?: string;
    title: string;
    name: string;
    education: Array<EducationEntry>;
    email: string;
    website?: string;
    experience: Array<ExperienceEntry>;
    summary: string;
    phone?: string;
    certifications: Array<Certification>;
    skills: Array<Skill>;
    location: string;
} {
    return {
        linkedIn: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.linkedIn)),
        title: value.title,
        name: value.name,
        education: from_candid_vec_n16(_uploadFile, _downloadFile, value.education),
        email: value.email,
        website: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.website)),
        experience: from_candid_vec_n19(_uploadFile, _downloadFile, value.experience),
        summary: value.summary,
        phone: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.phone)),
        certifications: from_candid_vec_n22(_uploadFile, _downloadFile, value.certifications),
        skills: value.skills,
        location: value.location
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    field: string;
    endDate: [] | [string];
    institution: string;
    degree: string;
    startDate: string;
}): {
    id: bigint;
    field: string;
    endDate?: string;
    institution: string;
    degree: string;
    startDate: string;
} {
    return {
        id: value.id,
        field: value.field,
        endDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.endDate)),
        institution: value.institution,
        degree: value.degree,
        startDate: value.startDate
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    endDate: [] | [string];
    description: string;
    company: string;
    achievements: Array<string>;
    location: string;
    startDate: string;
}): {
    id: bigint;
    title: string;
    endDate?: string;
    description: string;
    company: string;
    achievements: Array<string>;
    location: string;
    startDate: string;
} {
    return {
        id: value.id,
        title: value.title,
        endDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.endDate)),
        description: value.description,
        company: value.company,
        achievements: value.achievements,
        location: value.location,
        startDate: value.startDate
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: [] | [string];
    dateEarned: string;
    name: string;
    issuer: string;
}): {
    id: bigint;
    url?: string;
    dateEarned: string;
    name: string;
    issuer: string;
} {
    return {
        id: value.id,
        url: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.url)),
        dateEarned: value.dateEarned,
        name: value.name,
        issuer: value.issuer
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    thumbnailUrl: [] | [string];
    challenge: string;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    results: string;
    modality: _Modality;
    approach: string;
    deliverables: Array<string>;
}): {
    id: bigint;
    title: string;
    thumbnailUrl?: string;
    challenge: string;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    results: string;
    modality: Modality;
    approach: string;
    deliverables: Array<string>;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.thumbnailUrl)),
        challenge: value.challenge,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        results: value.results,
        modality: from_candid_Modality_n6(_uploadFile, _downloadFile, value.modality),
        approach: value.approach,
        deliverables: value.deliverables
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ilt: null;
} | {
    eLearning: null;
} | {
    hybrid: null;
} | {
    jobAid: null;
}): Modality {
    return "ilt" in value ? Modality.ilt : "eLearning" in value ? Modality.eLearning : "hybrid" in value ? Modality.hybrid : "jobAid" in value ? Modality.jobAid : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EducationEntry>): Array<EducationEntry> {
    return value.map((x)=>from_candid_EducationEntry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExperienceEntry>): Array<ExperienceEntry> {
    return value.map((x)=>from_candid_ExperienceEntry_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Certification>): Array<Certification> {
    return value.map((x)=>from_candid_Certification_n23(_uploadFile, _downloadFile, x));
}
function to_candid_Modality_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Modality): _Modality {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    thumbnailUrl?: string;
    challenge: string;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    results: string;
    modality: Modality;
    approach: string;
    deliverables: Array<string>;
}): {
    id: bigint;
    title: string;
    thumbnailUrl: [] | [string];
    challenge: string;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    results: string;
    modality: _Modality;
    approach: string;
    deliverables: Array<string>;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnailUrl: value.thumbnailUrl ? candid_some(value.thumbnailUrl) : candid_none(),
        challenge: value.challenge,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        results: value.results,
        modality: to_candid_Modality_n10(_uploadFile, _downloadFile, value.modality),
        approach: value.approach,
        deliverables: value.deliverables
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Modality): {
    ilt: null;
} | {
    eLearning: null;
} | {
    hybrid: null;
} | {
    jobAid: null;
} {
    return value == Modality.ilt ? {
        ilt: null
    } : value == Modality.eLearning ? {
        eLearning: null
    } : value == Modality.hybrid ? {
        hybrid: null
    } : value == Modality.jobAid ? {
        jobAid: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
